# Generated by Django 3.2 on 2021-05-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_assisted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(max_length=800)),
            ],
            options={
                'verbose_name_plural': 'Assisted Section',
            },
        ),
    ]
