# Generated by Django 3.2 on 2021-05-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0003_shows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shows',
            options={'verbose_name_plural': 'Shows Section'},
        ),
        migrations.AlterField(
            model_name='shows',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
